### ISSUE TITLE
move to an organization instead

### ISSUE THREAD

**Issue by JounQin** [import-js/eslint-import-resolver-typescript#115]
A personal GitHub repository lacks permission control well, GitHub Actions secrets for example, I'd like to move this project into @import-js if @ljharb agree, or @typescript-eslint if @bradzacher agree. Otherwise I'd like to move it to @un-ts

 cc @alexgorbatchev 

Can you help to migrate?

**Comment by alexgorbatchev** [comment]
Sure thing. Which one?

**Comment by bradzacher** [comment]
I remember around 3 years ago (when I contributed to this project) I spoke to Alex about this and they agreed. But when they tried to transfer to my personal account so I could move it forward, the transfer failed as I had a fork of the repo. Then we just never got around to trying again.

However today TBH I'm not sure if it belongs in @typescript-eslint.
The most common usages usages for an import resolver in `eslint-plugin-import` are rules [we don't really recommend](https://typescript-eslint.io/docs/linting/troubleshooting#eslint-plugin-import) for performance reasons and because TS already covers the checks.
The others rules are valid to use - but rarely used in comparison.

Given how tightly this is integrated with the plugin - maybe @import-js is the best place for it?

**Comment by JounQin** [comment]
> Sure thing. Which one?

@alexgorbatchev 

You can transfer it to @un-ts first, so that I'll have the permission to change later, then let's wait @ljharb's response.

**Comment by JounQin** [comment]
@bradzacher Right, this resolver works with/without `typescript-eslint`, @import-js is preferred, otherwise @un-ts then.

**Comment by ljharb** [comment]
I'm happy to have it live in import-js. I've invited @alexgorbatchev to the org.

**Comment by alexgorbatchev** [comment]
done!

**Comment by JounQin** [comment]
@ljharb Can you give me some permission so that I can manage GitHub Actions secrets in this repository?

**Comment by ljharb** [comment]
@JounQin that should do it.

**Comment by JounQin** [comment]
> @JounQin that should do it.

Thanks!
