### ISSUE TITLE
eslint-import-resolver-typescript v3.6.3 is not released

### ISSUE THREAD

**Issue by ocavue** [import-js/eslint-import-resolver-typescript#306]
Although the latest `package.json` in the Git repo has `3.6.3` as the version number, the latest published version in NPM is still `3.6.1`, which was published 10 months ago. 

https://github.com/import-js/eslint-import-resolver-typescript/blob/c9b5626ee69bd529c7e391e40928a4fb28dce179/package.json#L3

**Comment by Peeja** [comment]
This appears to be because https://github.com/import-js/eslint-import-resolver-typescript/commit/cecec359343a5b975e596dc11b9caae0455232aa#diff-e813096d69c49812e40e00be9ac8fa14d77f0ec1f97ab4c45cb096b3bedd35de deleted the `.npmrc`.

* Related issue: https://github.com/changesets/action/issues/98
* One repo's solution: https://github.com/pantheon-systems/decoupled-kit-js/pull/612/files (adds `.npmrc` to the repo)
* Another repo's solution: https://github.com/meilisearch/meilisearch-js-plugins/pull/983/files (adds `.npmrc` during CI run)

We _do_ have [`NPM_TOKEN` in the `env`](https://github.com/import-js/eslint-import-resolver-typescript/blob/c9b5626ee69bd529c7e391e40928a4fb28dce179/.github/workflows/release.yml#L44C11-L44C20), but we also need `//registry.npmjs.org/:_authToken=${NPM_TOKEN}` in `.npmrc` by the time `changesets` runs.

**Comment by nbouvrette** [comment]
I presume until version `3.6.3` is available `eslint-plugin-import-x` is not supported meaning that `ESLint 9` is also not supported? I'm getting all sort of npm errors right now when trying to upgrade.

**Comment by SukkaW** [comment]
I assume that the npm token has expired. But since I do not have access to the npm package, so I can't use my token instead.

**Comment by robtaylor** [comment]
I worked around this with ` npm rm https://github.com/import-js/eslint-import-resolver-typescript/tarball/3dfad60`

**Comment by SukkaW** [comment]
> I'm getting all sort of npm errors right now when trying to upgrade.

Just blame npm. In short, npm is bad. Yarn and pnpm both believe peerDeps conflicts should be warnings, not errors, and I believe that, too. Use `--legacy-peer-deps` is a viable workaround.

**Comment by SukkaW** [comment]
> We _do_ have [`NPM_TOKEN` in the `env`](https://github.com/import-js/eslint-import-resolver-typescript/blob/c9b5626ee69bd529c7e391e40928a4fb28dce179/.github/workflows/release.yml#L44C11-L44C20), but we also need `//registry.npmjs.org/:_authToken=${NPM_TOKEN}` in `.npmrc` by the time `changesets` runs.

`actions/setup-node` should have done this automatically, this is not the root cause.

**Comment by nbouvrette** [comment]
Thanks @SukkaW `npm install --legacy-peer-deps` seems to have bypassed the problem. Having said this, I presume once `3.6.3` (or newer) is released, this should no longer be required?

**Comment by JounQin** [comment]
@ljharb I believe I had `admin` role previously on this repository, can you change that back? So that I can check the `NPM_TOKEN` secret manually which I believe is not expired.

**Comment by ljharb** [comment]
You can't ever check a secret, only replace it. If you have a new value, I'll be happy to replace it for you.

**Comment by JounQin** [comment]
Hmm... I don't feel great to share a secret token.

**Comment by nbouvrette** [comment]
@ljharb is it possible to grand @JounQin back access so he casn try to replace the token himself? It's been over a month that this issue has been opened already

**Comment by ljharb** [comment]
yeah, that makes the most sense. done.

**Comment by JounQin** [comment]
released
