### ISSUE TITLE
feature request: FlatConfig support

### ISSUE THREAD

**Issue by Leonardo-Vieira-Andela** [import-js/eslint-import-resolver-typescript#318]
## What

We want to start using eslint-import + eslint-import-resolver-typescript but there is no flatConfig support. It would be very beneficial for said support to be added.

Kind regards!

**Comment by SukkaW** [comment]
If you are looking for import `eslint-import-resolver-typescript` directly without using path or string, plz check this proposal out: https://github.com/un-ts/eslint-plugin-import-x/issues/40#issuecomment-2381444266

I am going to implement that this weekend.

**Comment by SukkaW** [comment]
> This would be super helpful to have an example of how to use this package with the newer ESLint flat config (i.e. how do I use this package in an `eslint.config.js` file)

For `eslint-plugin-import-x`, the proposed usage would be:

```js
// eslint.config.js
import { importXTypeScriptResolver } from 'eslint-import-typescript-resolver';

// ...
settings: {
  'import-x/resolvers-next': [
     importXTypeScriptResolver(options)
  ]
}
/// ...
```

**Comment by melroy89** [comment]
> https://github.com/import-js/eslint-plugin-import#config---flat-eslintconfigjs

Yes I want something like `import importPlugin from 'eslint-import-resolver-typescript';` .. and then use it: `importPlugin.flatConfigs.recommended` or something within my `eslint.config.mjs` file.

**Comment by ljharb** [comment]
@melroy89 if you want the import plugin you'd need to import eslint-plugin-import; the resolver isn't same as the plugin.

**Comment by melroy89** [comment]
> [@melroy89](https://github.com/melroy89) if you want the import plugin you'd need to import eslint-plugin-import; the resolver isn't same as the plugin.

Thanks for you response! I se, I'm using my typescript project with [moduleResolution](https://www.typescriptlang.org/tsconfig/#moduleResolution) set to nodenext: `"moduleResolution": "NodeNext"`, and I use ES6 modules `"module": "NodeNext"`. Which works all great. But using `eslint-plugin-import` will result in that it can't find the imports.

Meaning the plugin has difficulties finding the `./somemodule.js` file (since well in TypeScript that JS file is indeed not there yet). `eslint-plugin-import` will fail to find it and unable to deal with this module resolution, hence I was thinking I needed this resolver-typescript plugin would help me out, I believe you mentioned that somewhere in an issue ticket at the eslint-plugin-import repository.

ps. I'm also using SWC during fast development (and tsc for production builds).

**Comment by SukkaW** [comment]
@melroy89 You can vote up my proposal at https://github.com/un-ts/eslint-plugin-import-x/issues/40#issuecomment-2381444266 which will resolve your issue. You will be able to use `eslint-import-resolver-typescript` w/ `eslint-plugin-import-x` like this: https://github.com/import-js/eslint-import-resolver-typescript/issues/318#issuecomment-2492885603

**Comment by mcshaman** [comment]
The problem I have found as somebody who is not familiar with ESLint configs trying to wrap my head around two types of config at the same time because various plugins support, promote and document in different ways.

I am setting up an ESLint config from scratch using the init tool so I will be using the new flat file format (which took a tone of reading to work out what the difference is). I need it to support my TS aliases so thats why I'm looking at `slint-import-resolver-typescript`.

I too like the OP thought it needed an exported flat config module because that how all the other plugins I have implemented so far work. Digging deeper based on @ljharb comment I assume it needs to be added to a confing object though I'm not sure how. It would be helpful at the very least if there was an example in the readme of implementing this plugin for flat config.

This is what I have so far but it doesn't seem to be working:
```
import pluginImportX from "eslint-plugin-import-x";

export default [
	{
		...pluginImportX.flatConfigs.recommended,
		settings: {
			"import-x/parsers": {
				"@typescript-eslint/parser": [".ts", ".tsx"],
			},
			"import-x/resolver": {
				typescript: {
					alwaysTryTypes: true,
				},
			},
		},
	},
]
```
So I am trying to extend the import-x flat config and add the `eslint-import-resolver-typescript` config from the readme. But yeah... Doesn't work and I don't know why or if I'm doing it right/wrong. Do I need to import `eslint-import-resolver-typescript`?

**Comment by SukkaW** [comment]
The flat config support for custom resolvers is implemented here at `eslint-plugin-import-x`: https://github.com/un-ts/eslint-plugin-import-x/pull/192

This allows you to use require/import or any js objects as the import resolver. The new resolver design of `eslint-plugin-import-x` will also allow the creation of a reusable resolver instance across many `resolve` function invocations to improve performance.

The `eslint-import-resolver-typescript` will also adapt the new resolver design soon!

**Comment by devuxer** [comment]
> https://github.com/un-ts/eslint-plugin-import-x#configuration-new-eslintconfigjs
> 
> https://github.com/import-js/eslint-plugin-import#config---flat-eslintconfigjs
> 
> Not sure what's your meaning.

@JounQin,

The documentation for this project (eslint-import-resolver-typescript) says:

> Configuration: Add the following to your **.eslintrc** config:

The problem is that .eslintrc is deprecated. The new way is to use eslint.config.mjs. How do we configure eslint-plugin-import with the typescript resolver to work with the new flat eslint.config files?

Most people using TypeScript and ESLint will want to use the new [typescript-eslint config](https://typescript-eslint.io/getting-started/), so examples for all of this together would be especially helpful.

**Comment by devuxer** [comment]
> I finally got `eslint-import-resolver-typescript` working with my flat file. Posted about it in [this related issue](https://github.com/import-js/eslint-import-resolver-typescript/issues/317#issuecomment-2513266250).

Glad you figured it out. I have to admit that after a lot of Googling and not really finding any good solutions, I decided to just give up and try [Biome](https://biomejs.dev/). Very good experience so far. All the plugins, resolvers, etc. we need to install and manually configure with ESLint are built in and just work. Also, I wasn't really suffering from the performance of ESLint on any of my projects (which are not huge), but Biome is seriously fast.
